language: node_js
dist: bionic
os:
- linux
- osx
node_js:
- "12"
cache: npm
script:
- lerna bootstrap
- lerna run test
deploy:
  - provider: npm
    email: subosito@gmail.com
    api_key:
      secure: Lnlnf7yY5ZeQL87InCLPknyVDHhAaESssIiVtQv18C6UX7vcg8Jgm+ke4Y17wFD2wOt5x3CL3WMyAy/QRiZ3GR56Im57dw0NM0VhbqLokg3QjAGRCN2Wu5basTAcHqcgZtu+3CBlNpkiY3YgcZfcVv4AutQNAl9LHkZ89F1m2D5OzXj9JomUrjR8YAG38dJLxf1gbxiP9glPiKOKKY1kjJRA6ZuWQ4M/S6MP6MvXVwIbCFvlJ8gRtngveCPVDKon+jvSHVuZUdFfRROdD4sxX7YGjNULmJ7sv4a5oN67Kqp109OtY2Fg11FOFpZ6kUzkfNtAnLtNWogUihT7M0lnEvWmUr4FhZiqgQ9JN7iVGdyxA6zTZ871qScRVgkh3UnF0MHZdyprTdBCtFQ6s9l1Hj3L9Q9whvD+cc5xUYt9b+pnqRpkcC2/4iI7NEBROS2i7tkkIlp8O5BT7rwU8rqnmi81SSsb3MqZqYZ6y6P7IaEq5ctTwrDd1VbjroZV8ueKHoIM1NTnyB07vm/fnVxMpD5AQzAZXjEcjqDaqWbJ5jqSDe04tTo/tWzo+HbNcoriBc1bqlWQUTnANDK6EbTJkZLxgONLNSUKT3Acl8tmVnu9Odt64Su79mr69/imf0FhDlFPz9+5TSHIWZu5f2FG7aCae5P+AVWV73YGjMOEKy0=
    on:
      tags: true
      repo: bukalapak/snowboard
      condition: $TRAVIS_OS_NAME = linux
