name: Main workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        env:
          cache-name: npm-v1582109828
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}
          restore_keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}
            ${{ runner.os }}-npm-
      - run: npm ci
      - run: npm run lint
      - run: npm run bootstrap
      - run: npm run build
      - run: npm test
