name: Main workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v1582184255
          restore-keys: |
            ${{ runner.os }}-npm-v1582184255
            ${{ runner.os }}-npm-
      - run: npm ci
      - run: npm run lint
      - run: npm run bootstrap
      - run: npm run build
      - run: npm test
      - run: npm run pack-linux
        if: runner.os == 'Linux'
      - run: npm run pack-darwin
        if: runner.os == 'macOS'
